### ISSUE TITLE
How to add an option for custom git bin location

### ISSUE THREAD

**Issue by Sertion** [alessioalex/git-blame#5]
I have created [a pull request to add a parameter](https://github.com/alessioalex/git-spawned-stream/pull/2) to [`git-spawned-stream`](https://github.com/alessioalex/git-spawned-stream) for a custom git binary location. How should we proceed to add it here?

I can see two options:
1. Add to the `option` array
2. Add an additional parameter

Keeping the options clean from non-git-parameter-options is the main reason to keep it separate.

**Comment by alessioalex** [comment]
@Sertion I agree with you, I think we should keep it separate. I've merged your pull request and published version `1.0.0` for `git-spawned-stream` so you can also update that dependency. Thank you for all your pull requests, your help is much appreciated.

**Comment by alessioalex** [comment]
Took the liberty of implementing this myself via https://github.com/alessioalex/git-blame/commit/77915ba541a1e1a7d25582f2d5160a6bd7543a1e and published version `1.4.0` to npm. Let me know if that's ok with you.

**Comment by Sertion** [comment]
Looks great!
